#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2001
#shellcheck disable=SC2155

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __gstash_header() {

	local op="${1}"
	local cmd="gstash${1}"
	local msg="${cmd} | enter: ${op} stash | ?: toggle preview"
	local colorMsgL1="${UNDERLINE}${MAGENTA}gstash${op}${RESET} | \
${BLUE}enter:${RESET} ${op} stash | \
${BLUE}?:${RESET} toggle preview"
	local spaces="$(echo "${cmd}" | sed -e 's/./ /g')"
	local colorMsgL2="${spaces} | ${BLUE}esc:${RESET} quit"

	local edge="$(echo "${msg}" | sed -e 's/./-/g')"
	local GSTASH_HEADER="${edge}"'
'"${colorMsgL1}"'
'"${colorMsgL2}"'
'"${edge}"'
 '

	echo "${GSTASH_HEADER}"
}