#!/bin/bash

#shellcheck disable=SC2034	# appears unused. Verify use (or export if used externally)
#shellcheck disable=SC1091	# Not following: was not specified as input (see shellcheck -x)

source "${__CUSTOM_CONSOLE_UTIL}"/__print_err

# Usage: __get_nouns "add"
function __get_nouns() {

	local verb="${1}"
	case "${verb}" in
		"show/view")
			NOUN_ARR=("1. status" "2. uncommitted changes" "3. commit logs/history")
		;;
		"add")
			NOUN_ARR=("1. new changes")
		;;
		"restore")
			NOUN_ARR=("1. staged changes" "2. unstaged changes")
		;;
		*)
			__print_err "[__get_nouns] unknown verb: ${verb}"
		;;
	esac
}