#!/bin/bash

#shellcheck disable=SC1091	# Not following: was not specified as input (see shellcheck -x)
#shellcheck disable=SC2155	# Declare and assign separately to avoid masking return values

source "$__CUSTOM_GIT_UTIL"/custom-git-explorer/__get_url

# Usage: __open_web_page "add" "1. new changes"
function __open_web_page() {

	local verb="${1}"
	local noun="${2/*. /}"
	local url="$(__get_url "${verb}" "${noun}")"
	[ -z "${url}" ] && return

	if command -v open >/dev/null 2>&1; then
		open "${url}"
	elif command -v xdg-open >/dev/null 2>&1; then
		xdg-open "${url}" &> /dev/null
	else
		__print_info "URL: ${url}"
	fi
}