#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __description_header() {

    local colorMsg="Write a short summary\n\n"
    colorMsg="${colorMsg}${BLUE}?:${RESET} toggle hint, ${BLUE}esc:${RESET} exit"

    local edge="-----------------------------------------------------------------------------------"
    local GCOMMIT_DESCRIPTION_HEADER="${edge}\n${colorMsg}\n "

    echo -e "${GCOMMIT_DESCRIPTION_HEADER}"
}