#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __new_scope_header() {

    local colorMsg="Enter the new commit scope (e.g. component or file name)\n"
    colorMsg="${colorMsg}${BLUE}<esc>: ${RESET}takes you back one step, "
    colorMsg="${colorMsg}${BLUE}<enter>: ${RESET}adds the new commit scope to the list\n\n"
    colorMsg="${colorMsg}${UNDERLINE}${MAGENTA}gcommit${RESET} follows ${BLUE}https://www.conventionalcommits.org/${RESET}"

    local msg="<esc>: takes you back one step, <enter>: adds the new commit scope to the list"
    local edge="$(echo "${msg}" | sed "s/./-/g")"
    local GCOMMIT_SCOPE_HEADER="${edge}\n${colorMsg}"

    echo -e "${GCOMMIT_SCOPE_HEADER}"
}