#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __scope_header() {

    local colorMsg="${UNDERLINE}${MAGENTA}gcommit${RESET} follows ${BLUE}https://www.conventionalcommits.org/${RESET} \n"
    colorMsg="${colorMsg}${BLUE}<enter>: ${RESET}selects the commit scope, "
    colorMsg="${colorMsg}${BLUE}<esc>: ${RESET}skips this step\n\n"
    colorMsg="${colorMsg}What is the scope of this change? (e.g. component or file name)"

    local msg="What is the scope of this change? (e.g. component or file name)"
    local edge="$(echo "${msg}" | sed "s/./-/g")"
    local GCOMMIT_SCOPE_HEADER="${edge}\n${colorMsg}\n${edge}\n "

    echo -e "${GCOMMIT_SCOPE_HEADER}"
}