#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __type_header() {

    local isBreakingChange="${1}"

    local colorMsg="${UNDERLINE}${MAGENTA}gcommit${RESET} follows ${BLUE}https://www.conventionalcommits.org/${RESET} \n"
    colorMsg="${colorMsg}${BLUE}<enter>: ${RESET}selects the commit type, "
    colorMsg="${colorMsg}${BLUE}<?>: ${RESET}toggles type definition, "
    colorMsg="${colorMsg}${BLUE}<esc>: ${RESET}exits\n\n"

    if [[ "${isBreakingChange}" == "false" ]]; then
        colorMsg="${colorMsg}Select the type of change that you're committing"
    else
        colorMsg="${colorMsg}Select the type of ${BLUE}BREAKING-CHANGE${RESET} that you're committing"
    fi

	local msg="<enter>: selects the commit type, <?>: toggles type definition, <esc>: exits"
    local edge="$(echo "${msg}" | sed "s/./-/g")"
    local GCOMMIT_TYPE_HEADER="${edge}\n${colorMsg}\n${edge}\n "

    echo -e "${GCOMMIT_TYPE_HEADER}"
}