#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __ask_header() {

    local question="${1}"

    local colorMsg="${BLUE}<enter>: ${RESET}selects an option, "
    colorMsg="${colorMsg}${BLUE}<esc>: ${RESET}exits\n\n"
    colorMsg="${colorMsg}${question}"

    local msg="<enter>: selects an option, <esc>: exits"
    local edge="$(echo "${msg}" | sed "s/./-/g")"
    ASK_HEADER="${edge}\n${colorMsg}\n "

    echo -e "${ASK_HEADER}"
}