#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2001
#shellcheck disable=SC2155

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __gadd_header() {

	local msg="gadd | enter: stage file(s) | tab: select multiple files | ctrl-r: refresh diff"
	local colorMsgL1="${UNDERLINE}${MAGENTA}gadd${RESET} | \
${BLUE}enter:${RESET} stage file(s) | \
${BLUE}tab:${RESET} select multiple files | \
${BLUE}ctrl-r:${RESET} refresh diff"
	local colorMsgL2="       ${BLUE}?:${RESET} toggle preview | \
${BLUE}q/esc:${RESET} quit"

	local edge="$(echo "${msg}" | sed -e 's/./-/g')"
	local GADD_HEADER="${edge}"'
'"${colorMsgL1}"'
'"${colorMsgL2}"'
'"${edge}"'
 '

	echo "${GADD_HEADER}"
}