#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __gcommit_type_header() {

    local isBreakingChange="${1}"
	local msg="<enter>: select commit type, <?>: toggle type definition, <esc>: quit"

    local colormsg="${UNDERLINE}${MAGENTA}gcommit${RESET} follows ${BLUE}https://www.conventionalcommits.org/${RESET} \n\
${BLUE}<enter>: ${RESET}select commit type, \
${BLUE}<?>: ${RESET}toggle type definition, \
${BLUE}<esc>: ${RESET}quit\n\n"

    if [[ "${isBreakingChange}" == "false" ]]; then
        colormsg="${colormsg}Select the type of change that you're committing"
    else
        colormsg="${colormsg}Select the type of ${BLUE}BREAKING-CHANGE${RESET} that you're committing"
    fi

    local edge="$(echo "${msg}" | sed "s/./-/g")"
    local GCOMMIT_TYPE_HEADER="${edge}\n${colormsg}\n${edge}\n "
    echo -e "${GCOMMIT_TYPE_HEADER}"
}