#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2001
#shellcheck disable=SC2155

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __gdiff_header() {

	local msg="gdiff | enter: git diff | ctrl-r: refresh diff | ?: toggle preview | q/esc: quit"
	local colormsg="${UNDERLINE}${MAGENTA}gdiff${RESET} | \
${BLUE}enter:${RESET} git diff | \
${BLUE}ctrl-r:${RESET} refresh diff | \
${BLUE}?:${RESET} toggle preview | \
${BLUE}q/esc:${RESET} quit"

	local edge="$(echo "${msg}" | sed -e 's/./-/g')"
	local GDIFF_HEADER="${edge}"'
'"${colormsg}"'
'"${edge}"'
 '

	echo "${GDIFF_HEADER}"
}