#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2001
#shellcheck disable=SC2155

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __grestore_header() {

	local msg="grestore | <tab>: select multiple files, <enter>: restore modified file(s) / remove new files, <?>: toggle preview, <q/esc>: quit"
	local colormsg="${UNDERLINE}${MAGENTA}grestore${RESET} | \
${BLUE}<tab>: ${RESET}select multiple files, \
${BLUE}<enter>: ${RESET}restore modified file(s) / remove new files, \
${BLUE}<?>: ${RESET}toggle preview, \
${BLUE}<q/esc>: ${RESET}quit"

	local edge="$(echo "${msg}" | sed -e 's/./-/g')"
	local GRESTORE_HEADER="${edge}"'
'"${colormsg}"'
'"${edge}"'
 '

	echo "${GRESTORE_HEADER}"
}