#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2001
#shellcheck disable=SC2155

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __grestorestaged_header() {

	local msg="grestorestaged | enter: restore staged file(s) | q/esc: quit   "
	local colorMsgL1="${UNDERLINE}${MAGENTA}grestorestaged${RESET} | \
${BLUE}enter: ${RESET}restore staged file(s) | \
${BLUE}q/esc: ${RESET}quit"
	local colorMsgL2="                 ${BLUE}tab: ${RESET}select multiple files | \
${BLUE}?: ${RESET}toggle preview"

	local edge="$(echo "${msg}" | sed -e 's/./-/g')"
	local GRESTORESTAGED_HEADER="${edge}"'
'"${colorMsgL1}"'
'"${colorMsgL2}"'
'"${edge}"'
 '

	echo "${GRESTORESTAGED_HEADER}"
}