#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2001
#shellcheck disable=SC2155

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __grestore_header() {

	local msg="grestore | enter: restore modified file(s) / remove new file(s) | q/esc: quit "
	local colorMsgL1="${UNDERLINE}${MAGENTA}grestore${RESET} | \
${BLUE}enter:${RESET} restore modified file(s) / restore new file(s) | \
${BLUE}q/esc:${RESET} quit"
	local colorMsgL2="           ${BLUE}tab: ${RESET}select multiple files | \
${BLUE}?: ${RESET}toggle preview"

	local edge="$(echo "${msg}" | sed -e 's/./-/g')"
	local GRESTORE_HEADER="${edge}"'
'"${colorMsgL1}"'
'"${colorMsgL2}"'
'"${edge}"'
 '

	echo "${GRESTORE_HEADER}"
}