#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2001
#shellcheck disable=SC2155

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __gstash_header() {

	local msg="gstashapply | enter: apply stash | ?: toggle preview"
	local colorMsgL1="${UNDERLINE}${MAGENTA}gstashapply${RESET} | \
${BLUE}enter:${RESET} apply stash | \
${BLUE}?:${RESET} toggle preview"
	local colorMsgL2="            | ${BLUE}esc:${RESET} quit"

	local edge="$(echo "${msg}" | sed -e 's/./-/g')"
	local GSTASH_HEADER="${edge}"'
'"${colorMsgL1}"'
'"${colorMsgL2}"'
'"${edge}"'
 '

	echo "${GSTASH_HEADER}"
}