#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "${__CUSTOM_CONSOLE_UTIL}"/__common	# for colors

# Usage: __select_branch_header "gswitch" "select local branch" "exit"
function __select_branch_header() {

	local cmd="${1}"
	local cmdMsg="${2}"
	local escAction="${3}"
	local colorMsg="${MAGENTA}${UNDERLINE}${cmd}${RESET} | ${cmdMsg}\n\n"
	colorMsg="${colorMsg}${BLUE}esc:${RESET} ${escAction} "

	local x="${cmd} | ${cmdMsg}"
	local edge="$(echo "${x}" | sed "s/./-/g")"
	local HEADER="${edge}\n${colorMsg}\n${edge}\n "

	echo -e "${HEADER}"
}