#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __prefix_header() {

    local colorMsg="(optional) Give a prefix to the branch name (e.g. issue number / JIRA ticket etc.)\n"
    colorMsg="${colorMsg}${BLUE}<esc>: ${RESET}skips the prefix, "
    colorMsg="${colorMsg}${BLUE}<enter>: ${RESET}starts the branch name with the input prefix\n\n"
    colorMsg="${colorMsg}${UNDERLINE}${MAGENTA}gbranchout${RESET} follows the format ${MAGENTA}[optional prefix]${BLUE}/[optional type]/<branch_name>${RESET}"

    local msg="(optional) Give a prefix to the branch name (e.g. issue number / JIRA ticket etc.)"
    local edge="$(echo "${msg}" | sed "s/./-/g")"
    local GBRANCHOUT_PREFIX_HEADER="${edge}\n${colorMsg}"

    echo -e "${GBRANCHOUT_PREFIX_HEADER}"
}