#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __type_header() {

    local colorMsg="${BLUE}<?>:${RESET} help, ${BLUE}<esc>:${RESET} skip branch type"

	local msg="<?>: help, <esc>: skip branch type"
    local edge="$(echo "${msg}" | sed "s/./-/g")"
    local TYPE_HEADER="${edge}\n${colorMsg}\n${edge}\n "

    echo -e "${TYPE_HEADER}"
}