#!/bin/bash

#shellcheck disable=SC2155
#shellcheck disable=SC1091

source "${__CUSTOM_GIT_UTIL}"/__common
source "$__CUSTOM_CONSOLE_UTIL"/__split_str
source "$__CUSTOM_CONSOLE_UTIL"/__trim_double_quotes

function __gdiff_preview() {

	local str="${1}"

	if [[ ${str:0:1} != "R" && ${str:1:1} != "R" ]]; then
		local file=${str#"${str:0:3}"}		# Remove prefix
		file="$(__trim_double_quotes "${file}")"

		if [[ ${str:0:1} != " " ]];then		# file is staged
			git diff --cached --color -- "${file}" | ${CUSTOM_GIT_PAGER}
		fi
		if [[ ${str:1:1} != " " ]];then		# file is unstaged
			git diff --color -- "${file}" | ${CUSTOM_GIT_PAGER}
		fi
		return
	fi

	local files=${str#"${str:0:3}"}		# Remove prefix
	__split_str "${files}" " -> "
	local oldFile=""
	local newFile=""
	for item in "${RESULT_ARR[@]}"; do
		local file="$(__trim_double_quotes "${item}")"
		if [[ -z "${oldFile}" ]]; then
			oldFile="${file}"
		else
			newFile="${file}"
		fi
	done

	if [[ ${str:0:1} == "R" ]]; then
		git diff --cached --color -- "${oldFile}" "${newFile}" | ${CUSTOM_GIT_PAGER}

		if [[ ${str:1:1} != " " ]]; then
			git diff --color -- "${newFile}" | ${CUSTOM_GIT_PAGER}
		fi
	else
		git diff --color -- "${oldFile}" "${newFile}" | ${CUSTOM_GIT_PAGER}
	fi
}