#!/bin/bash

#shellcheck disable=SC2155
#shellcheck disable=SC1091	# Not following: ./__common was not specified as input (see shellcheck -x)

source "${__CUSTOM_GIT_UTIL}"/__common

function __gshow_preview() {

	local str="${1}"
	local commitSHA="$(echo "$str" | grep -E "[0-9a-z]+" -o | head -n 1)"
	if [[ -z "${commitSHA}" ]]; then
		return
	fi
	git show --color=always "${commitSHA}" | ${CUSTOM_GIT_PAGER}
}