#!/bin/bash

#shellcheck disable=SC2155
#shellcheck disable=SC2001 # See if you can use ${variable//search/replace}


function __gstash_preview() {

	local str="${1}"
	local stashId="$(echo "$str" | sed 's/\:.*//g')"
	git stash show -p --color=always "${stashId}" | ${CUSTOM_GIT_PAGER}
}