#!/bin/bash

# shellcheck disable=SC1091
# shellcheck disable=SC2155

source "${__CUSTOM_GIT_UTIL}"/fzf_headers/__ask_header

function __ask() {

    local question="${1}"
    local options=("yes" "no")

    local ASK_HEADER="$(__ask_header "${question}")"
    local choice="$(printf "%s\n" "${options[@]}"  |\
                    fzf --height 10%\
                        --info=hidden\
                        --header "${ASK_HEADER}")"
    echo "${choice}"
}