#!/bin/bash

#shellcheck disable=SC2155  # Declare and assign separately to avoid masking return values.
#shellcheck disable=SC1091  # Not following: ./fzf_headers/__select_branch_header was not specified as input (see shellcheck -x)

source "${__CUSTOM_GIT_UTIL}"/fzf_headers/__select_branch_header

# Usage: __select_local_branch "gswitch" "select local branch to switch to" "exit"
function __select_local_branch() {

    local cmd="${1}"
    local cmdMsg="${2}"
    local escAction="${3}"
    local HEADER="$(__select_branch_header "${cmd}" "${cmdMsg}" "${escAction}")"
    local branchName="$(git branch --sort=-committerdate |\
                        fzf --height=50%\
                            --header "${HEADER}" |\
                        sed 's/^. //g')"

    local rawBranchNameFile="$(getrawstr "${branchName}")"
    echo "${rawBranchNameFile}" | xargs -I "{}" echo {}     # xargs used to handle "invalid reference" for special characters
                                                            # like ', '#' in branch names
}