#!/usr/bin/env bash

#shellcheck disable=SC1091      # Not following: ./__println_as was not specified as input (see shellcheck -x)

source "$__CUSTOM_CONSOLE_UTIL"/__println_as
source "$__CUSTOM_CONSOLE_UTIL"/__common

function __type_preview() {

    local commit_type="${1}"

    case "${commit_type}" in
        feat) __println_as bold "${commit_type}: A new feature"
        ;;
        fix) __println_as bold "${commit_type}: A bug fix"
        ;;
        perf) __println_as bold "${commit_type}: A code change that improves performance"
        ;;
        refactor) __println_as bold "${commit_type}: A code change that neither fixes a bug nor adds a feature"
        ;;
        test) __println_as bold "${commit_type}: Add missing tests or correct existing tests"
        ;;
        style) __println_as bold "${commit_type}: Changes that do not affect the meaning of the code (white-space, formatting, missing semicolons, etc)"
        ;;
        docs) __println_as bold "${commit_type}: Documentation only changes"
        ;;
        build) __println_as bold "${commit_type}: Changes that affect the build system or external dependencies"
        ;;
        ci) __println_as bold "${commit_type}: Changes to the CI configuration files and scripts"
        ;;
        cd) __println_as bold "${commit_type}: Changes to the CD configuration files and scripts"
        ;;
        BREAKING-CHANGE) __println_as bold "${commit_type}: Introduce a breaking API change"
        ;;
        *) __println_as bold "Unknown commit type"
        ;;
    esac

    local colorMsg="[optional <prefix>]/${MAGENTA}[optional <type>]${RESET}/<name>\n"
    colorMsg="${colorMsg}${MAGENTA}\t\t\t\t\t\t\t\t│${RESET}\n"
    colorMsg="${colorMsg}${MAGENTA}\t\t\t\t\t\t\t\t└─⫸ "
    colorMsg="${colorMsg}type of branch you're creating${RESET}"
    echo -e "\n${colorMsg}"
}