#!/usr/bin/env bash

# shellcheck disable=SC1091

# ensure the command is run in a git repo
source __assertgitrepo

function main() {

    __assertgitrepo

    numUnstagedFiles=$(git status --short | grep "^[ ?]" -c)
    if [[ $numUnstagedFiles -eq 0 ]]; then
        gstatus
        printf "\n[INFO] No unstaged files.\n"
        return
    fi

    # use command line arguments if provided
    if [[ $# -gt 0 ]]; then
        [[ "$1" == "." ]] && git add -A || git add $*
        gstatus
        return
    fi

    git status --short | grep "^[ ?]" | fzf -m --color 'fg:160' | sed -e 's/...//' | xargs git add
    # TODO: check status of this command here (fzf, xargs or git add might fail)

    gstatus
}

main $*
