#!/usr/bin/env bash

# shellcheck disable=SC1091

# ensure the command is run in a git repo
source __assertgitrepo

function main() {

    __assertgitrepo

    if [[ $# -gt 0 ]]; then
        # use command line arguments
        git add $*
    else
        stage_modified_files
        stage_untracked_files
    fi

    gstatus
}

function stage_modified_files() {

    numModifiedFiles=$(git status --short | grep "^[ ]" -c)
    if [[ $numModifiedFiles -eq 0 ]]; then
        return
    fi
    gstatus
    echo
    read -p "stage modified files? (press enter / n) : " -r
    if [[ $REPLY != "" ]]; then
        return
    fi
    git status --short | grep "^[ ]" | sed -e 's/ [A-Z] //' | \
        fzf -m --color='fg:9' | xargs git add
}

function stage_untracked_files() {

    numUntrackedFiles=$(git status --short | grep "^??" -c)
    if [[ $numUntrackedFiles -eq 0 ]]; then
        return
    fi
    gstatus
    echo
    read -p "stage untracked files? (press enter / n) : " -r
    if [[ $REPLY != "" ]]; then
        return
    fi
    git status --short | grep "^??" | sed -e 's/^[?]* //' | \
        fzf -m --color='fg:9' | xargs git add
}

main $*
