#!/bin/bash

function main() {

    if [[ $# -gt 0 ]]; then
        git add $*
        gstatus
        return
    fi

    numUnstagedFiles=$(git status --short | grep "^[ ?]" -c)
    if [[ $numUnstagedFiles -eq 0 ]]; then
        gstatus
        printf "\n[INFO] No unstaged files.\n"
        return
    fi

    git status --short | grep "^[ ?]" | fzf -m --color 'fg:160' | sed -e 's/...//' | xargs git add
    gstatus
}

main $*
