#!/bin/bash

#shellcheck disable=SC1091 # Not following: ./__assertgitrepo was not specified as input
#shellcheck disable=SC2155 # Declare and assign separately to avoid masking return values
#shellcheck disable=SC2001 # See if you can use ${variable//search/replace}

source "${__CUSTOM_GIT_UTIL}"/fzf_headers/__gstash_header
source "${__CUSTOM_GIT_UTIL}"/__assertgitrepo

__assertgitrepo

function main() {

	local GSTASH_HEADER="$(__gstash_header)"

	local selectedStr="$(git stash list | \
							fzf --bind '?:toggle-preview'\
								--header "${GSTASH_HEADER}"\
								--preview "source ${__CUSTOM_GIT_UTIL}/fzf_previews/__gstash_preview; __gstash_preview {}")"
	[ -z "${selectedStr}" ] && return

	local stashId="$(echo "${selectedStr}" | sed 's/\:.*//g')"
	git stash apply "${stashId}"

	git status
}

main