#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __name_header() {

    local msg="(optional) Give a prefix to the branch name (e.g. issue number / JIRA ticket etc.)"
    local edge="$(echo "${msg}" | sed "s/./-/g")"
    local GBRANCH_NAME_HEADER="${edge}\n"

    local colorMsg="${UNDERLINE}${MAGENTA}gbranch${RESET} follows the format ${BLUE}[optional prefix]/<type>/<branch_name>${RESET} \n"
    colorMsg="${colorMsg}${BLUE}<enter>: ${RESET}Creates the new branch, "
    colorMsg="${colorMsg}${BLUE}<esc>: ${RESET}exit\n\n"
    colorMsg="${colorMsg}What is the branch name?"
    GBRANCH_NAME_HEADER="${GBRANCH_NAME_HEADER}${colorMsg}"

    echo -e "${GBRANCH_NAME_HEADER}"
}