#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __type_header() {

    local colorMsg="${UNDERLINE}${MAGENTA}gbranch${RESET} follows the format ${BLUE}[optional prefix]/[optional type]/<branch_name>${RESET} \n"
    colorMsg="${colorMsg}${BLUE}<enter>: ${RESET}selects the branch type, "
    colorMsg="${colorMsg}${BLUE}<?>: ${RESET}toggles type definition, "
    colorMsg="${colorMsg}${BLUE}<esc>: ${RESET}skips this step\n\n"
    colorMsg="${colorMsg}Select the type of branch"

	local msg="<enter>: selects the branch type, <?>: toggles type definition, <esc>: skips this step"
    local edge="$(echo "${msg}" | sed "s/./-/g")"
    local GBRANCH_TYPE_HEADER="${edge}\n${colorMsg}\n${edge}\n "

    echo -e "${GBRANCH_TYPE_HEADER}"
}