#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __prefix_header() {

    local colorMsg="Write a prefix\n\n"
    colorMsg="${colorMsg}${BLUE}esc:${RESET} skip prefix, ${BLUE}?:${RESET} toggle hint"

    local msg="esc: skip prefix, ?: toggle hint"
    local edge="$(echo "${msg}" | sed "s/./-/g")"
    local GBRANCHCREATE_HEADER="${edge}\n${colorMsg}\n "

    echo -e "${GBRANCHCREATE_HEADER}"
}