#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __prefix_header() {

    local colorMsg="Write a prefix\n\n"
    colorMsg="${colorMsg}${BLUE}<?>:${RESET} help, ${BLUE}<esc>:${RESET} skip prefix"

    local msg="<?>: help, <esc>: skip prefix"
    local edge="$(echo "${msg}" | sed "s/./-/g")"
    local GBRANCHCREATE_HEADER="${edge}\n${colorMsg}\n "

    echo -e "${GBRANCHCREATE_HEADER}"
}