#!/bin/bash

#shellcheck disable=SC1091
#shellcheck disable=SC2155
#shellcheck disable=SC2001

source "$__CUSTOM_CONSOLE_UTIL"/__common

function __type_header() {

    local colorMsg="${BLUE}esc:${RESET} skip type, ${BLUE}?:${RESET} toggle hint"

	local msg="esc: skip type, ?: toggle hint"
    local edge="$(echo "${msg}" | sed "s/./-/g")"
    local TYPE_HEADER="${edge}\n${colorMsg}\n${edge}\n "

    echo -e "${TYPE_HEADER}"
}